# @package _global_

algo:
  config:
    eval_callbacks:
      analysis_plot_cb:
        _target_: humanoidverse.agents.callbacks.analysis_plot_decoupled_motion_tracking.AnalysisPlotDecoupledMotionTracking
        config:
          sim_dt: 0.02
          log_single_robot: False
          plot_update_interval: 100
          use_weblogger: False
          compute_metrics: True