# @package _global_

algo:
  config:
    eval_callbacks:
      analysis_plot_cb:
        _target_: humanoidverse.agents.callbacks.analysis_plot_decoupled_force_estimator.AnalysisPlotDecoupledForceEstimator
        config:
          sim_dt: 0.02
          log_single_robot: True
          plot_update_interval: 100