ROBOT_TYPE: 'g1_29dof' # Robot name, "go2", "b2", "b2w", "h1", "go2w", "g1" 
# ROBOT_SCENE: "../humanoidverse/data/robots/g1/scene_29dof.xml" # Robot scene, for Sim2Sim
ROBOT_SCENE: "../humanoidverse/data/robots/g1/scene_29dof_freebase.xml" # Robot scene, for Sim2Sim
# ROBOT_SCENE: "../humanoidverse/data/robots/g1/scene_29dof_freebase_camera.xml" # Robot scene, for Sim2Sim
# ROBOT: "../humanoidverse/data/robots/g1/g1_29dof.urdf" # Robot URDF file
ASSET_ROOT: "../humanoidverse/data/robots/g1" # Robot Asset Root
# ASSET_FILE: "g1_29dof.urdf" # Robot Asset File
ASSET_FILE: "g1_29dof_fakehand_freebase.urdf" # Robot Asset File
### REAL
# DOMAIN_ID: 0 # Domain id
# # Interface (Yuanhang: this can be commented out)
# INTERFACE: "en0"

## SIM
DOMAIN_ID: 0 # Domain id
# Interface (Yuanhang: this can NOT be commented out)
INTERFACE: "lo" # Yuanhang: in simulation, lo0 for mac, lo for linux

USE_ROS: False # Use ROS

FREE_BASE: True

PRINT_SCENE_INFORMATION: True # Print link, joint and sensors information of robot
ENABLE_ELASTIC_BAND: True # Virtual spring band, used for lifting h1

SIMULATE_DT: 0.005  # Need to be larger than the runtime of viewer.sync()
VIEWER_DT: 0.02  # Viewer update time
USE_SENSOR: False
USE_HISTORY: True # True

USE_JOYSTICK: 1 # Simulate Unitree WirelessController using a gamepad (0: disable, 1: enable)
JOYSTICK_TYPE: "xbox" # support "xbox" and "switch" gamepad layout
JOYSTICK_DEVICE: 0 # Joystick number

VISUALIZE_PIN: False
VISUALIZE_FORCES: False
SRB_SOLVER: "DYNAMICS_Z" # SRB_Z, SRB_SIMPLE, SRB_FULL, DYNAMICS, DYNAMICS_Z

GAIT_PERIOD: 1.0 # 1.25

MOTOR2JOINT: [0, 1, 2, 3, 4, 5,
              6, 7, 8, 9, 10, 11,
              12, 13, 14, 
              15, 16, 17, 18, 19, 20, 21, 
              22, 23, 24, 25, 26, 27, 28]
            
JOINT2MOTOR: [0, 1, 2, 3, 4, 5,
              6, 7, 8, 9, 10, 11,
              12, 13, 14, 
              15, 16, 17, 18, 19, 20, 21, 
              22, 23, 24, 25, 26, 27, 28]
            

UNITREE_LEGGED_CONST:
  HIGHLEVEL: 0xEE
  LOWLEVEL: 0xFF
  TRIGERLEVEL: 0xF0
  PosStopF: 2146000000.0
  VelStopF: 16000.0
  MODE_MACHINE: 5
  MODE_PR:  0

JOINT_KP: [
    100, 100, 100, 200, 20, 20,
    100, 100, 100, 200, 20, 20,
    300, 300, 300,
    90, 60, 20, 60, 4, 4, 4,
    90, 60, 20, 60, 4, 4, 4
]

JOINT_KD: [
   2.5, 2.5, 2.5, 5, 0.2, 0.1,
   2.5, 2.5, 2.5, 5, 0.2, 0.1,
   5.0, 5.0, 5.0,
   2.0, 1.0, 0.4, 1.0, 0.2, 0.2, 0.2,
    2.0, 1.0, 0.4, 1.0, 0.2, 0.2, 0.2
]

MOTOR_KP: [
    100, 100, 100, 200, 20, 20,
    100, 100, 100, 200, 20, 20,
    300, 300, 300,
    90, 60, 20, 60, 4, 4, 4,
    90, 60, 20, 60, 4, 4, 4
]

MOTOR_KD: [
   2.5, 2.5, 2.5, 5, 0.2, 0.1,
   2.5, 2.5, 2.5, 5, 0.2, 0.1,
   5.0, 5.0, 5.0,
   2.0, 1.0, 0.4, 1.0, 0.2, 0.2, 0.2,
    2.0, 1.0, 0.4, 1.0, 0.2, 0.2, 0.2
]

WeakMotorJointIndex:
  left_hip_yaw_joint: 0
  left_hip_roll_joint: 1
  left_hip_pitch_joint: 2
  left_knee_joint: 3
  left_ankle_pitch_joint: 4
  left_ankle_roll_joint: 5
  right_hip_yaw_joint: 6
  right_hip_roll_joint: 7
  right_hip_pitch_joint: 8
  right_knee_joint: 9
  right_ankle_pitch_joint: 10
  right_ankle_roll_joint: 11
  waist_yaw_joint : 12
  waist_roll_joint : 13
  waist_pitch_joint : 14
  left_shoulder_pitch_joint: 15
  left_shoulder_roll_joint: 16
  left_shoulder_yaw_joint: 17
  left_elbow_joint: 18
  left_wrist_roll_joint: 19
  left_wrist_pitch_joint: 20
  left_wrist_yaw_joint: 21
  right_shoulder_pitch_joint: 22
  right_shoulder_roll_joint: 23
  right_shoulder_yaw_joint: 24
  right_elbow_joint: 25
  right_wrist_roll_joint: 26
  right_wrist_pitch_joint: 27
  right_wrist_yaw_joint: 28

NUM_MOTORS: 29
NUM_JOINTS: 29
NUM_UPPER_BODY_JOINTS: 14

DEFAULT_DOF_ANGLES: [
    -0.1,  # left_hip_pitch_joint 
    0.0,  # left_hip_roll_joint
    0.0,  # left_hip_yaw_joint
    0.3,  # left_knee_joint
    -0.2, # left_ankle_pitch_joint
    0.0,  # left_ankle_roll_joint
    -0.1, # right_hip_pitch_joint
    0.0,  # right_hip_roll_joint
    0.0,  # right_hip_yaw_joint
    0.3,  # right_knee_joint
    -0.2, # right_ankle_pitch_joint
    0.0,  # right_ankle_roll_joint
    0.0,  # waist_yaw_joint
    0.0,  # waist_roll_joint
    0.0,  # waist_pitch_joint
    0.0,  # left_shoulder_pitch_joint
    0.0,  # left_shoulder_roll_joint
    0.0,  # left_shoulder_yaw_joint
    0.0,  # left_elbow_joint
    0.0,  # left_wrist_roll_joint
    0.0,  # left_wrist_pitch_joint
    0.0,  # left_wrist_yaw_joint
    0.0,  # right_shoulder_pitch_joint
    0.0,  # right_shoulder_roll_joint
    0.0,  # right_shoulder_yaw_joint
    0.0,  # right_elbow_joint
    0.0,  # right_wrist_roll_joint
    0.0,  # right_wrist_pitch_joint
    0.0   # right_wrist_yaw_joint
]

DEFAULT_MOTOR_ANGLES: [
    -0.1,  # left_hip_pitch_joint 
    0.0,  # left_hip_roll_joint
    0.0,  # left_hip_yaw_joint
    0.3,  # left_knee_joint
    -0.2, # left_ankle_pitch_joint
    0.0,  # left_ankle_roll_joint
    -0.1, # right_hip_pitch_joint
    0.0,  # right_hip_roll_joint
    0.0,  # right_hip_yaw_joint
    0.3,  # right_knee_joint
    -0.2, # right_ankle_pitch_joint
    0.0,  # right_ankle_roll_joint
    0.0,  # waist_yaw_joint
    0.0,  # waist_roll_joint
    0.0,  # waist_pitch_joint
    0.0,  # left_shoulder_pitch_joint
    0.0,  # left_shoulder_roll_joint
    0.0,  # left_shoulder_yaw_joint
    0.0,  # left_elbow_joint
    0.0,  # left_wrist_roll_joint
    0.0,  # left_wrist_pitch_joint
    0.0,  # left_wrist_yaw_joint
    0.0,  # right_shoulder_pitch_joint
    0.0,  # right_shoulder_roll_joint
    0.0,  # right_shoulder_yaw_joint
    0.0,  # right_elbow_joint
    0.0,  # right_wrist_roll_joint
    0.0,  # right_wrist_pitch_joint
    0.0   # right_wrist_yaw_joint
]

motor_pos_lower_limit_list: [-2.5307, -0.5236, -2.7576, -0.087267, -0.87267, -0.2618, 
                             -2.5307, -2.9671, -2.7576, -0.087267, -0.87267, -0.2618, 
                             -2.618, -0.52, -0.52,
                             -3.0892, -1.5882, -2.618, -1.0472, 
                             -1.972222054, -1.61443, -1.61443,
                             -3.0892, -2.2515, -2.618, -1.0472, 
                             -1.972222054, -1.61443, -1.61443]
motor_pos_upper_limit_list: [2.8798, 2.9671, 2.7576, 2.8798, 0.5236, 0.2618, 
                            2.8798, 0.5236, 2.7576, 2.8798, 0.5236, 0.2618, 
                            2.618, 0.52, 0.52,
                            2.6704, 2.2515, 2.618, 2.0944, 
                            1.972222054, 1.61443, 1.61443,
                            2.6704, 1.5882, 2.618, 2.0944, 
                            1.972222054, 1.61443, 1.61443]
motor_vel_limit_list: [32.0, 32.0, 32.0, 20.0, 37.0, 37.0, 
                      32.0, 32.0, 32.0, 20.0, 37.0, 37.0, 
                      32.0, 37.0, 37.0, 
                      37.0, 37.0, 37.0, 37.0, 
                      37.0, 22.0, 22.0,
                      37.0, 37.0, 37.0, 37.0, 
                      37.0, 22.0, 22.0]
motor_effort_limit_list: [88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 
                        88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 
                        88.0, 50.0, 50.0,
                        25.0, 25.0, 25.0, 25.0, 
                        25.0, 5.0, 5.0,
                        25.0, 25.0, 25.0, 25.0, 
                        25.0, 5.0, 5.0]
history_config: 
    history_actor: {
      base_ang_vel: 4,
      projected_gravity: 4,
      command_lin_vel: 4,
      command_ang_vel: 4,
      command_stand: 4,
      command_base_height: 4,
      command_waist_dofs: 4,
      ref_upper_dof_pos: 4,
      dof_pos: 4,
      dof_vel: 4,
      actions: 4,
      # sin_phase: 4,
      # cos_phase: 4,
      # phase_time: 4,
    }

    history_estimator: {
      base_ang_vel: 9,
      projected_gravity: 9,
      command_lin_vel: 9,
      command_ang_vel: 9,
      command_stand: 9,
      command_base_height: 9,
      command_waist_dofs: 9,
      ref_upper_dof_pos: 9,
      dof_pos: 9,
      # dof_vel: 9,
      actions: 9,
      # sin_phase: 9,
      # cos_phase: 9,
      left_ee_comp: 9,
      right_ee_comp: 9,
    }

obs_dims: {
            base_lin_vel: 3,
            base_ang_vel: 3,
            projected_gravity: 3,
            command_lin_vel: 2,
            command_ang_vel: 1,
            command_stand: 1,
            command_base_height: 1,
            command_waist_dofs: 3,
            ref_upper_dof_pos: 14, # upper body actions
            dof_pos: 29,
            dof_vel: 29,
            actions: 15, # lower body actions
            phase_time: 1,
            sin_phase: 1,
            cos_phase: 1,
            apply_force: 1,
            left_ee_apply_force: 3,
            right_ee_apply_force: 3,
            left_ee_estimated_force: 3,
            right_ee_estimated_force: 3,
            left_ee_comp: 14,
            right_ee_comp: 14,
          }
obs_scales: {
  base_orientation: 1.0,
  base_lin_vel: 2.0,
  base_ang_vel: 0.25,
  projected_gravity: 1.0,
  command_lin_vel: 1.0,
  command_ang_vel: 1.0,
  command_stand: 1.0,
  command_base_height: 2.0,
  command_waist_dofs: 1.0,
  ref_upper_dof_pos: 1.0,
  dof_pos: 1.0,
  dof_vel: 0.05,
  actions: 1.0,
  sin_phase: 1.0,
  cos_phase: 1.0,
  phase_time: 1.0,
  left_ee_apply_force: 0.1,
  right_ee_apply_force: 0.1,
  left_ee_estimated_force: 0.1,
  right_ee_estimated_force: 0.1,
  left_ee_comp: 0.1,
  right_ee_comp: 0.1,
  history_actor: 1.0,
  history_critic: 1.0,
  history_estimator: 1.0,
  apply_force_scale: 1.0,
  apply_or_estimated_force: 1.0,
}

force_range:
  apply_force_x_range: [-15.0, 15.0]
  apply_force_y_range: [-15.0, 15.0]
  apply_force_z_range: [-50.0, 5.0]