# server_address: 192.168.123.164
# server_address: 127.0.0.1
# server_address: 172.26.113.104
# server_address: 192.168.1.166
server_address: 172.26.23.182
image_show: False
img_config: {
            'fps': 30,
            'head_camera_type': 'mujoco',
            'head_camera_image_shape': [480, 640],  # Head camera resolution
            'head_camera_id_numbers': [0],
            # 'fps': 30,
            # 'head_camera_type': 'opencv',
            # 'head_camera_image_shape': [480, 680],  # Head camera resolution
            # 'head_camera_id_numbers': [4],
            # 'wrist_camera_type': 'opencv',
            # 'wrist_camera_image_shape': [480, 640],  # Wrist camera resolution
            # 'wrist_camera_id_numbers': [2, 4],
            }